default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: kodets_development

test:
  <<: *default
  database: kodets_test

production:
  <<: *default
  database: kodets_production
  username: kodets
  password: <%= ENV['KODETS_DATABASE_PASSWORD'] %>
